- hosts: host1
  name: netplan host1
  become: yes
  gather_facts: no
  tasks:
    - name: cloud file entering host1
      ansible.builtin.file:
        path: /etc/netplan/config.yaml
        state: absent
    - name: copy netplan yaml host1
      copy:
        src: ./host1.yaml
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml host1
      shell: netplan apply
       
    - name: Check interface 2 host1
      shell: /sbin/ip -br -4 a | grep 'eth2'
      ignore_errors: yes
      register: result
    - debug: msg={{ result.stdout }}

- hosts: host2
  name: netplan host2
  become: yes
  gather_facts: no
  tasks:
    - name: cloud file entering host2
      ansible.builtin.file:
        path: /etc/netplan/config.yaml
        state: absent 
    - name: copy netplan yaml host2
      copy:
        src: ./host2.yaml
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml host2
      shell: netplan apply
       
    - name: Check interface 2
      shell: /sbin/ip -br -4 a | grep 'eth2'
      ignore_errors: yes
      register: result
    - debug: msg={{ result.stdout }}
    
- hosts: host3
  name: netplan host3
  become: yes
  gather_facts: no
  tasks:
    - name: cloud file entering host3
      ansible.builtin.file:
        path: /etc/netplan/config.yaml
        state: absent
    - name: copy netplan yaml host3
      copy:
        src: ./host3.yaml
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply
       
    - name: Check interface 2 host3
      shell: /sbin/ip -br -4 a | grep 'eth2'
      ignore_errors: yes
      register: result
    - debug: msg={{ result.stdout }}
    
- hosts: host4
  name: netplan host4
  become: yes
  gather_facts: no
  tasks:
    - name: cloud file entering host4
      ansible.builtin.file:
        path: /etc/netplan/config.yaml
        state: absent
    - name: copy netplan yaml host4
      copy:
        src: ./host4.yaml
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply
       
    - name: Check interface 2 host4
      shell: /sbin/ip -br -4 a | grep 'eth2'
      ignore_errors: yes
      register: result
    - debug: msg={{ result.stdout }}
    