- header:
    model: VX
    nvue-api-version: nvue_v1
    rev-id: 1.0
    version: Cumulus Linux 5.8.0
- set:
    bridge:
      domain:
        br_default:
          vlan:
            '10':
              vni:
                '10': {}
            '20':
              vni:
                '20': {}
    evpn:
      enable: on
    interface:
      lo:
        ip:
          address:
            172.16.100.1/32: {}
        type: loopback
      swp1-2,8-9:
        type: swp
      swp8:
        bridge:
          domain:
            br_default:
              access: 10
      swp9:
        bridge:
          domain:
            br_default:
              access: 20
    nve:
      vxlan:
        enable: on
        source:
          address: 172.16.100.1
    router:
      bgp:
        autonomous-system: 65101
        enable: on
        router-id: 172.16.100.1
    system:
      config:
        auto-save:
          enable: on
      hostname: leaf1
    vrf:
      default:
        router:
          bgp:
            address-family:
              ipv4-unicast:
                enable: on
                network:
                  172.16.18.0/24: {}
                  172.16.19.0/24: {}
                  172.16.100.1/32: {}
              l2vpn-evpn:
                enable: on
            enable: on
            neighbor:
              swp1:
                address-family:
                  l2vpn-evpn:
                    enable: on
                remote-as: external
                type: unnumbered
              swp2:
                address-family:
                  l2vpn-evpn:
                    enable: on
                remote-as: external
                type: unnumbered