- header:
    model: VX
    nvue-api-version: nvue_v1
    rev-id: 1.0
    version: Cumulus Linux 5.8.0
- set:
    evpn:
      enable: on
    interface:
      lo:
        ip:
          address:
            172.16.100.3/32: {}
        type: loopback
      swp1-2:
        type: swp
    nve:
      vxlan:
        enable: on
    router:
      bgp:
        autonomous-system: 65100
        enable: on
        router-id: 172.16.100.3
    system:
      config:
        auto-save:
          enable: on
      hostname: spine3
    vrf:
      default:
        router:
          bgp:
            address-family:
              ipv4-unicast:
                enable: on
                network:
                  172.16.100.3/32: {}
              l2vpn-evpn:
                enable: on
            enable: on
            neighbor:
              swp1:
                address-family:
                  l2vpn-evpn:
                    enable: on
                remote-as: external
                type: unnumbered
              swp2:
                address-family:
                  l2vpn-evpn:
                    enable: on
                remote-as: external
                type: unnumbered