- hosts: host1,host2,host3,host4
  name: startup
  become: yes
  gather_facts: no
  ignore_errors: yes
  tasks:
    - name: install net-tools traceroute on hosts
      shell: sudo apt update && sudo apt install net-tools traceroute -y